'use client';
import { useState } from 'react';
import { useAppData, dataStore } from '@/lib/store';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { UserRound, Save } from 'lucide-react';
import type { TrainerProfile } from '@/lib/types';
import { uid } from '@/lib/utils';
export default function TrainerProfilePage(){const d=useAppData();const old=d.trainerProfiles?.[0];const [p,setP]=useState<TrainerProfile>(old||{id:uid('trainer'),name:'',bio:'',achievements:[],specialties:[],pricePerSession:0,sharePercent:20,whatsapp:'',instagram:'',telegram:'',status:'pending'});const [msg,setMsg]=useState('');const save=()=>{if(!p.name.trim()){setMsg('نام مربی الزامی است.');return}dataStore.saveData({trainerProfiles:[p,...(d.trainerProfiles||[]).filter(x=>x.id!==p.id)]});setMsg('پروفایل مربی ذخیره شد و برای نمایش عمومی آماده است.');};return <div dir="rtl" className="container mx-auto max-w-3xl space-y-6 p-6"><div><h1 className="text-2xl font-bold"><UserRound className="ml-2 inline"/>پروفایل حرفه‌ای مربی</h1><p className="text-muted-foreground">این اطلاعات در بخش کشف مربیان برای شاگردان نمایش داده می‌شود.</p></div><Card><CardHeader><CardTitle>مشخصات عمومی و حرفه‌ای</CardTitle></CardHeader><CardContent className="grid gap-4"><div className="grid gap-3 md:grid-cols-2"><div><Label>نام و نام خانوادگی</Label><Input value={p.name} onChange={e=>setP({...p,name:e.target.value})}/></div><div><Label>لینک عکس پروفایل</Label><Input dir="ltr" value={p.avatar||''} onChange={e=>setP({...p,avatar:e.target.value})}/></div><div><Label>قیمت هر جلسه</Label><Input type="number" value={p.pricePerSession} onChange={e=>setP({...p,pricePerSession:Number(e.target.value)})}/></div><div><Label>درصد سهم باشگاه</Label><Input type="number" min="0" max="100" value={p.sharePercent} onChange={e=>setP({...p,sharePercent:Math.min(100,Math.max(0,Number(e.target.value)))})}/></div></div><Textarea placeholder="معرفی و رزومه کوتاه" value={p.bio||''} onChange={e=>setP({...p,bio:e.target.value})}/><Input placeholder="تخصص‌ها با ، جدا شوند" value={(p.specialties||[]).join('،')} onChange={e=>setP({...p,specialties:e.target.value.split('،').map(x=>x.trim()).filter(Boolean)})}/><Input placeholder="افتخارات با ، جدا شوند" value={(p.achievements||[]).join('،')} onChange={e=>setP({...p,achievements:e.target.value.split('،').map(x=>x.trim()).filter(Boolean)})}/><div className="grid gap-3 md:grid-cols-3"><Input dir="ltr" placeholder="WhatsApp" value={p.whatsapp||''} onChange={e=>setP({...p,whatsapp:e.target.value})}/><Input dir="ltr" placeholder="Instagram URL" value={p.instagram||''} onChange={e=>setP({...p,instagram:e.target.value})}/><Input dir="ltr" placeholder="Telegram URL" value={p.telegram||''} onChange={e=>setP({...p,telegram:e.target.value})}/></div><Button onClick={save}><Save className="ml-1 h-4 w-4"/>ذخیره پروفایل</Button>{msg&&<p className="text-primary">{msg}</p>}</CardContent></Card></div>}
