'use client';
import { useMemo, useState } from 'react';
import { useAppData, dataStore } from '@/lib/store';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Search, CalendarDays, Wallet, Dumbbell, Utensils, MessageCircle, Instagram } from 'lucide-react';
import type { TrainerProfile, TrainerBooking, WorkoutPlan, NutritionPlan } from '@/lib/types';
import { hasTrainerConflict, splitTrainerPayment } from '@/lib/trainer';
const id=()=>`${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
export default function TrainerMarketplace(){const d=useAppData(); const trainers=d.trainerProfiles||[]; const [q,setQ]=useState(''); const [selected,setSelected]=useState<TrainerProfile|null>(trainers[0]||null); const [book,setBook]=useState({date:'',time:'08:00',endTime:'09:00',height:'',weight:'',goal:'',allergies:''}); const [notice,setNotice]=useState(''); const found=useMemo(()=>trainers.filter(t=>t.status==='approved'&&(`${t.name} ${(t.specialties||[]).join(' ')}`).includes(q)),[trainers,q]);
 const reserve=()=>{if(!selected||!book.date){setNotice('مربی و تاریخ را انتخاب کنید.');return} const dayOfWeek=(new Date(`${book.date}T00:00:00`).getDay()+6)%7; const slots=(d.trainerAvailabilities||[]).filter(a=>a.trainerId===selected.id&&a.active&&a.dayOfWeek===dayOfWeek); if(slots.length && !slots.some(a=>book.time>=a.startTime&&book.endTime<=a.endTime)){setNotice('این ساعت در زمان‌های آزاد مربی نیست.');return} if(hasTrainerConflict(selected.id,book.date,book.time,book.endTime,d.trainerBookings||[],d.trainerHolidays||[])){setNotice('این زمان با رزرو یا تعطیلی مربی تداخل دارد.');return} const amount=selected.pricePerSession; const split=splitTrainerPayment(amount, selected.sharePercent ?? d.account.trainerAccounting?.defaultGymPercent ?? 20, d.account.trainerAccounting?.taxPercent ?? 0); const x:TrainerBooking={id:id(),trainerId:selected.id,customerId:d.customers[0]?.id||'customer',date:book.date,startTime:book.time,endTime:book.endTime,recurringMonthly:true,status:'pending',amount,gymShare:split.gym + split.tax,trainerShare:split.trainer,details:{height:Number(book.height)||undefined,weight:Number(book.weight)||undefined,goal:book.goal,allergies:book.allergies}}; const paid={...x,status:'paid' as const}; dataStore.saveData({trainerBookings:[...(d.trainerBookings||[]),paid],trainerWalletEntries:[...(d.trainerWalletEntries||[]),{id:id(),trainerId:x.trainerId,bookingId:x.id,at:new Date().toISOString(),amount:x.trainerShare,type:'earning' as const,description:'درآمد رزرو خصوصی ماهانه'}]});setNotice('پرداخت آزمایشی موفق شد؛ رزرو فعال و سهم مربی وارد کیف پول شد.');};
 return <div dir="rtl" className="container mx-auto space-y-6 p-6"><div><h1 className="text-2xl font-bold">بازار مربیان و خدمات اختصاصی</h1><p className="text-muted-foreground">کشف مربی، رزرو ماهانه، برنامه تمرینی و برنامه غذایی</p></div><Tabs defaultValue="discover"><TabsList className="grid grid-cols-4"><TabsTrigger value="discover">کشف مربی</TabsTrigger><TabsTrigger value="booking">رزرو و فرم سلامت</TabsTrigger><TabsTrigger value="plans">برنامه‌ها</TabsTrigger><TabsTrigger value="wallet">کیف پول مربی</TabsTrigger></TabsList>
 <TabsContent value="discover"><Card><CardHeader><CardTitle className="flex gap-2"><Search className="h-5 w-5"/>مربیان تأییدشده باشگاه</CardTitle><Input placeholder="جست‌وجوی نام یا تخصص" value={q} onChange={e=>setQ(e.target.value)}/></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">{found.map(t=><div key={t.id} className="rounded-lg border p-4"><div className="flex items-center justify-between"><div><h3 className="font-bold">{t.name}</h3><p className="text-sm text-muted-foreground">{(t.specialties||[]).join('، ')}</p></div><Badge>{t.pricePerSession.toLocaleString()} تومان</Badge></div><p className="mt-2 text-sm">{t.bio||'مربی تأییدشده باشگاه'}</p><div className="mt-3 flex gap-2"><Button onClick={()=>setSelected(t)}>انتخاب برای رزرو</Button>{t.whatsapp&&<Button variant="outline" asChild><a href={`https://wa.me/${t.whatsapp}`}><MessageCircle className="ml-1 h-4 w-4"/>واتساپ</a></Button>}{t.instagram&&<Button variant="outline" asChild><a href={t.instagram}><Instagram className="ml-1 h-4 w-4"/>اینستاگرام</a></Button>}</div></div>)}{!found.length&&<p className="text-muted-foreground">مربی تأییدشده‌ای برای نمایش ثبت نشده است.</p>}</CardContent></Card></TabsContent>
 <TabsContent value="booking"><Card><CardHeader><CardTitle><CalendarDays className="ml-2 inline h-5 w-5"/>رزرو تمام جلسات ماه در ساعت ثابت</CardTitle></CardHeader><CardContent className="space-y-4">{selected?<p>مربی انتخاب‌شده: <b>{selected.name}</b> — سهم باشگاه: {selected.sharePercent}٪</p>:<p>ابتدا از بخش کشف مربی، مربی را انتخاب کنید.</p>}<div className="grid gap-3 md:grid-cols-4"><div><Label>تاریخ شروع</Label><Input type="date" value={book.date} onChange={e=>setBook({...book,date:e.target.value})}/></div><div><Label>ساعت شروع / پایان</Label><Input type="time" value={book.time} onChange={e=>setBook({...book,time:e.target.value})}/><Input className="mt-1" type="time" value={book.endTime} onChange={e=>setBook({...book,endTime:e.target.value})}/></div><div><Label>قد / وزن</Label><Input placeholder="قد" value={book.height} onChange={e=>setBook({...book,height:e.target.value})}/><Input className="mt-1" placeholder="وزن" value={book.weight} onChange={e=>setBook({...book,weight:e.target.value})}/></div><div><Label>هدف و حساسیت</Label><Input placeholder="هدف" value={book.goal} onChange={e=>setBook({...book,goal:e.target.value})}/><Input className="mt-1" placeholder="حساسیت/آسیب" value={book.allergies} onChange={e=>setBook({...book,allergies:e.target.value})}/></div></div><Button onClick={reserve}>ثبت درخواست و ادامه پرداخت</Button>{notice&&<p className="text-sm text-primary">{notice}</p>}</CardContent></Card></TabsContent>
 <TabsContent value="plans"><div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle><Dumbbell className="ml-2 inline"/>سازنده برنامه تمرینی</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">برنامه‌های چندروزه، سیستم تمرینی، ست، تکرار، استراحت و یادداشت توسط مربی ثبت و برای شاگرد ارسال می‌شود.</p><Badge className="mt-4">{(d.workoutPlans||[]).length} برنامه ثبت‌شده</Badge></CardContent></Card><Card><CardHeader><CardTitle><Utensils className="ml-2 inline"/>سازنده برنامه غذایی</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">وعده، ساعت، کالری، یادداشت و چند تنوع غذایی برای هر وعده پشتیبانی می‌شود.</p><Badge className="mt-4">{(d.nutritionPlans||[]).length} برنامه ثبت‌شده</Badge></CardContent></Card></div></TabsContent>
 <TabsContent value="wallet"><Card><CardHeader><CardTitle><Wallet className="ml-2 inline"/>کیف پول خصوصی مربی</CardTitle></CardHeader><CardContent><p>این بخش فقط برای مربی صاحب حساب نمایش داده می‌شود.</p><p className="mt-3 text-xl font-bold">موجودی: {(d.trainerWalletEntries||[]).reduce((s,x)=>s+(x.type==='earning'?x.amount:-x.amount),0).toLocaleString()} تومان</p></CardContent></Card></TabsContent></Tabs></div>}
