'use client';
import { useState } from 'react';
import { useAppData, dataStore } from '@/lib/store';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { CalendarClock, Trash2 } from 'lucide-react';
import type { TrainerAvailability } from '@/lib/types';
import { uid } from '@/lib/utils';
const days=['شنبه','یکشنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنجشنبه','جمعه'];
export default function TrainerAvailabilityPage(){const d=useAppData();const trainerId=d.trainerProfiles?.[0]?.id||'trainer';const [rows,setRows]=useState<TrainerAvailability[]>(d.trainerAvailabilities?.filter(x=>x.trainerId===trainerId)||[]);const [form,setForm]=useState({day:'0',start:'08:00',end:'09:00'});const add=()=>{const x={id:uid('availability'),trainerId,dayOfWeek:Number(form.day),startTime:form.start,endTime:form.end,active:true};const next=[...rows,x];setRows(next);dataStore.saveData({trainerAvailabilities:[...(d.trainerAvailabilities||[]).filter(a=>a.trainerId!==trainerId),...next]});};const remove=(id:string)=>{const next=rows.filter(x=>x.id!==id);setRows(next);dataStore.saveData({trainerAvailabilities:[...(d.trainerAvailabilities||[]).filter(a=>a.trainerId!==trainerId),...next]});};return <div dir="rtl" className="container mx-auto max-w-3xl space-y-6 p-6"><h1 className="text-2xl font-bold"><CalendarClock className="ml-2 inline"/>تقویم زمان‌های آزاد مربی</h1><Card><CardHeader><CardTitle>افزودن زمان هفتگی</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-4"><div><Label>روز</Label><Select value={form.day} onValueChange={v=>setForm({...form,day:v})}><SelectTrigger/><SelectContent>{days.map((x,i)=><SelectItem key={i} value={String(i)}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>شروع</Label><Input type="time" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></div><div><Label>پایان</Label><Input type="time" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></div><Button className="mt-6" onClick={add}>افزودن زمان</Button></CardContent></Card><Card><CardHeader><CardTitle>زمان‌های ثبت‌شده</CardTitle></CardHeader><CardContent className="space-y-2">{rows.map(x=><div key={x.id} className="flex items-center justify-between rounded border p-3"><span>{days[x.dayOfWeek]} — {x.startTime} تا {x.endTime}</span><Button variant="ghost" size="icon" onClick={()=>remove(x.id)}><Trash2 className="h-4 w-4"/></Button></div>)}{!rows.length&&<p className="text-muted-foreground">زمانی ثبت نشده است.</p>}</CardContent></Card></div>}
