'use client';
import { useMemo, useState } from 'react';
import { useAppData, dataStore } from '@/lib/store';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Wallet, ArrowDownToLine } from 'lucide-react';
import { uid } from '@/lib/utils';
export default function TrainerWalletPage(){const d=useAppData();const trainer=d.trainerProfiles?.[0];const entries=d.trainerWalletEntries||[];const [amount,setAmount]=useState('');const [notice,setNotice]=useState('');const balance=useMemo(()=>entries.filter(e=>!trainer||e.trainerId===trainer.id).reduce((s,e)=>s+(e.type==='earning'?e.amount:-e.amount),0),[entries,trainer]);const withdraw=()=>{const n=Number(amount);if(!n||n<=0||n>balance){setNotice('مبلغ برداشت معتبر نیست یا موجودی کافی نیست.');return}const next=[...entries,{id:uid('withdraw'),trainerId:trainer?.id||'trainer',at:new Date().toISOString(),amount:n,type:'withdrawal' as const,status:'pending' as const,description:'درخواست برداشت مربی'}];dataStore.saveData({trainerWalletEntries:next});setAmount('');setNotice('درخواست برداشت ثبت شد و پس از تأیید مدیریت تسویه می‌شود.');};return <div dir="rtl" className="container mx-auto space-y-6 p-6"><div><h1 className="text-2xl font-bold">کیف پول مربی</h1><p className="text-muted-foreground">اطلاعات مالی این صفحه فقط برای حساب مربی نمایش داده می‌شود.</p></div><div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle className="text-sm">موجودی قابل برداشت</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold">{balance.toLocaleString()} تومان</p></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">تعداد تراکنش‌ها</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold">{entries.length}</p></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">وضعیت تسویه</CardTitle></CardHeader><CardContent><Badge>نیازمند تأیید مدیریت</Badge></CardContent></Card></div><Card><CardHeader><CardTitle><ArrowDownToLine className="ml-2 inline h-5 w-5"/>درخواست برداشت</CardTitle></CardHeader><CardContent className="flex max-w-md gap-2"><div className="flex-1"><Label>مبلغ</Label><Input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="تومان"/></div><Button className="mt-6" onClick={withdraw}>ثبت درخواست</Button></CardContent></Card><Card><CardHeader><CardTitle><Wallet className="ml-2 inline h-5 w-5"/>تاریخچه تراکنش‌ها</CardTitle></CardHeader><CardContent className="space-y-2">{entries.map(e=><div key={e.id} className="flex justify-between rounded border p-3"><span>{e.description}</span><span className={e.type==='earning'?'text-green-600':'text-red-600'}>{e.type==='earning'?'+':'-'}{e.amount.toLocaleString()} تومان</span></div>)}{!entries.length&&<p className="text-muted-foreground">تراکنشی ثبت نشده است.</p>}</CardContent></Card>{notice&&<p className="text-primary">{notice}</p>}</div>}
