'use client';

import { useState } from 'react';
import { useAppData, dataStore } from '@/lib/store';
import type { MemberSession, TaxSettings, SubscriptionSettings, TrainerHoliday } from '@/lib/types';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { FileCheck2, UsersRound, CreditCard, Plus, Trash2 } from 'lucide-react';

const uid = () => `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const emptyTax: TaxSettings = { enabled: false, invoiceMode: 'draft' };
const emptySub: SubscriptionSettings = { plan: 'trial', status: 'active' };

export default function CompliancePage() {
  const data = useAppData();
  const [tax, setTax] = useState(data.account.tax || emptyTax);
  const [formula, setFormula] = useState(data.account.trainerAccounting || { defaultGymPercent: 20, taxPercent: 0, employeeSharePercent: 0 });
  const [sub, setSub] = useState(data.account.subscription || emptySub);
  const [sessions, setSessions] = useState<MemberSession[]>(data.memberSessions || []);
  const [holidays, setHolidays] = useState<TrainerHoliday[]>(data.trainerHolidays || []);
  const [holiday, setHoliday] = useState({ date: '', title: '', scope: 'gym' as TrainerHoliday['scope'] });
  const addHoliday = () => { if (!holiday.date || !holiday.title.trim()) return; const next = [...holidays, { id: uid(), ...holiday, title: holiday.title.trim() }]; setHolidays(next); dataStore.saveData({ trainerHolidays: next }); setHoliday({ date: '', title: '', scope: 'gym' }); };
  const removeHoliday = (id: string) => { const next = holidays.filter(x => x.id !== id); setHolidays(next); dataStore.saveData({ trainerHolidays: next }); };
  const [inviteCode, setInviteCode] = useState(data.account.trainerInviteCode || '');
  const generateCode = () => { const code = String(Math.floor(100000 + Math.random() * 900000)); setInviteCode(code); save({ trainerInviteCode: code }); };
  const [draft, setDraft] = useState({ title: '', gender: 'male' as MemberSession['gender'], days: 'شنبه، دوشنبه، چهارشنبه', startTime: '08:00', endTime: '10:00', capacity: '30' });
  const save = (patch: Partial<typeof data.account>) => dataStore.saveData({ account: { ...data.account, ...patch } });
  const saveTax = () => { save({ tax }); alert('تنظیمات مالیاتی ذخیره شد.'); };
  const saveSub = () => { save({ subscription: sub }); alert('وضعیت اشتراک ذخیره شد.'); };
  const addSession = () => { if (!draft.title.trim()) return; const next = [...sessions, { ...draft, id: uid(), capacity: Number(draft.capacity) || 1, status: 'active' }]; setSessions(next); dataStore.saveData({ memberSessions: next }); setDraft({ ...draft, title: '' }); };
  const removeSession = (id: string) => { const next = sessions.filter(x => x.id !== id); setSessions(next); dataStore.saveData({ memberSessions: next }); };
  return <div className="container mx-auto space-y-6 p-6" dir="rtl">
    <div><h1 className="text-2xl font-bold">مرکز عملیات و انطباق</h1><p className="text-muted-foreground">مودیان، سانس‌های تفکیک‌شده و اشتراک مدیریت‌شده</p></div>
    <Tabs defaultValue="tax"><TabsList className="grid w-full grid-cols-3"><TabsTrigger value="tax"><FileCheck2 className="ml-2 h-4 w-4"/>مودیان و صندوق مکانیزه</TabsTrigger><TabsTrigger value="sessions"><UsersRound className="ml-2 h-4 w-4"/>سانس اعضا</TabsTrigger><TabsTrigger value="subscription"><CreditCard className="ml-2 h-4 w-4"/>اشتراک</TabsTrigger></TabsList>
      <TabsContent value="tax"><Card><CardHeader><CardTitle>پیکربندی صورتحساب الکترونیکی</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex items-center justify-between rounded-lg border p-4"><div><b>فعال‌سازی اتصال مودیان</b><p className="text-sm text-muted-foreground">صدور پیش‌نویس و آماده‌سازی ارسال به سامانه</p></div><Switch checked={tax.enabled} onCheckedChange={v=>setTax({...tax,enabled:v})}/></div><div className="grid gap-4 md:grid-cols-2"><div><Label>شناسه یکتای حافظه مالیاتی</Label><Input value={tax.taxpayerId||''} onChange={e=>setTax({...tax,taxpayerId:e.target.value})}/></div><div><Label>شناسه پایانه فروشگاهی</Label><Input value={tax.terminalId||''} onChange={e=>setTax({...tax,terminalId:e.target.value})}/></div><div><Label>نشانی API (اختیاری)</Label><Input placeholder="https://..." value={tax.apiUrl||''} onChange={e=>setTax({...tax,apiUrl:e.target.value})}/></div><div><Label>حالت صدور فاکتور</Label><Select value={tax.invoiceMode} onValueChange={v=>setTax({...tax,invoiceMode:v as TaxSettings['invoiceMode']})}><SelectTrigger/><SelectContent><SelectItem value="draft">پیش‌نویس داخلی</SelectItem><SelectItem value="manual">ارسال دستی</SelectItem><SelectItem value="online">ارسال آنلاین</SelectItem></SelectContent></Select></div></div><div className="rounded-lg border p-4"><b>فرمول سهم و کسورات</b><div className="mt-2 grid gap-3 md:grid-cols-3"><div><Label>سهم پیش‌فرض باشگاه (%)</Label><Input type="number" value={formula.defaultGymPercent} onChange={e=>setFormula({...formula,defaultGymPercent:Number(e.target.value)})}/></div><div><Label>مالیات مربی (%)</Label><Input type="number" value={formula.taxPercent} onChange={e=>setFormula({...formula,taxPercent:Number(e.target.value)})}/></div><div><Label>سهم کارکنان (%)</Label><Input type="number" value={formula.employeeSharePercent} onChange={e=>setFormula({...formula,employeeSharePercent:Number(e.target.value)})}/></div></div></div><Button onClick={()=>{saveTax();save({trainerAccounting:formula});}}>ذخیره تنظیمات مالیاتی و فرمول حسابداری</Button></CardContent></Card></TabsContent>
      <TabsContent value="sessions"><Card><CardHeader><CardTitle>سانس‌های تفکیک‌شده بر اساس جنسیت</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-6"><Input className="md:col-span-2" placeholder="عنوان سانس" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><Select value={draft.gender} onValueChange={v=>setDraft({...draft,gender:v as MemberSession['gender']})}><SelectTrigger/><SelectContent><SelectItem value="male">آقایان</SelectItem><SelectItem value="female">بانوان</SelectItem><SelectItem value="mixed">مختلط</SelectItem></SelectContent></Select><Input value={draft.days} onChange={e=>setDraft({...draft,days:e.target.value})}/><Input type="time" value={draft.startTime} onChange={e=>setDraft({...draft,startTime:e.target.value})}/><Button onClick={addSession}><Plus className="ml-1 h-4 w-4"/>افزودن</Button></div><div className="space-y-2">{sessions.map(s=><div key={s.id} className="flex items-center justify-between rounded border p-3"><div><b>{s.title}</b><span className="mr-3 text-sm text-muted-foreground">{s.gender==='male'?'آقایان':s.gender==='female'?'بانوان':'مختلط'} · {s.days} · {s.startTime} تا {s.endTime}</span></div><Button variant="ghost" size="icon" onClick={()=>removeSession(s.id)}><Trash2 className="h-4 w-4"/></Button></div>)}{!sessions.length&&<p className="text-muted-foreground">هنوز سانسی ثبت نشده است.</p>}</div><div className="border-t pt-4"><h3 className="mb-2 font-semibold">تعطیلات باشگاه و مربیان</h3><div className="grid gap-2 md:grid-cols-4"><Input type="date" value={holiday.date} onChange={e=>setHoliday({...holiday,date:e.target.value})}/><Input placeholder="عنوان تعطیلی" value={holiday.title} onChange={e=>setHoliday({...holiday,title:e.target.value})}/><Select value={holiday.scope} onValueChange={v=>setHoliday({...holiday,scope:v as TrainerHoliday['scope']})}><SelectTrigger/><SelectContent><SelectItem value="gym">تعطیلی کل باشگاه</SelectItem><SelectItem value="trainer">تعطیلی مربی</SelectItem></SelectContent></Select><Button onClick={addHoliday}>ثبت تعطیلی</Button></div><div className="mt-2 space-y-1">{holidays.map(h=><div key={h.id} className="flex justify-between rounded border p-2 text-sm"><span>{h.date} — {h.title} ({h.scope==='gym'?'باشگاه':'مربی'})</span><Button variant="ghost" size="sm" onClick={()=>removeHoliday(h.id)}>حذف</Button></div>)}</div></div></CardContent></Card></TabsContent>
      <TabsContent value="subscription"><Card><CardHeader><CardTitle>اشتراک مدیریت‌شده</CardTitle></CardHeader><CardContent className="space-y-4"><div className="rounded-lg border p-4"><b>کد دعوت مربیان</b><p className="text-sm text-muted-foreground">این کد را فقط در اختیار مربیان مورد اعتماد قرار دهید.</p><div className="mt-2 flex gap-2"><Input dir="ltr" readOnly value={inviteCode} placeholder="هنوز تولید نشده"/><Button onClick={generateCode}>تولید کد ۶ رقمی</Button></div></div><div className="flex gap-2"><Badge>{sub.status==='active'?'فعال':sub.status}</Badge><Badge variant="outline">طرح {sub.plan}</Badge></div><div className="grid gap-4 md:grid-cols-3"><div><Label>طرح</Label><Select value={sub.plan} onValueChange={v=>setSub({...sub,plan:v as SubscriptionSettings['plan']})}><SelectTrigger/><SelectContent>{['trial','basic','pro','enterprise'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>وضعیت</Label><Select value={sub.status} onValueChange={v=>setSub({...sub,status:v as SubscriptionSettings['status']})}><SelectTrigger/><SelectContent><SelectItem value="active">فعال</SelectItem><SelectItem value="past_due">در انتظار تمدید</SelectItem><SelectItem value="suspended">تعلیق‌شده</SelectItem><SelectItem value="cancelled">لغوشده</SelectItem></SelectContent></Select></div><div><Label>تاریخ اعتبار</Label><Input type="date" value={sub.validUntil||''} onChange={e=>setSub({...sub,validUntil:e.target.value})}/></div></div><p className="text-sm text-muted-foreground">این سامانه وضعیت را ثبت می‌کند و هیچ برداشت خودکاری انجام نمی‌دهد.</p><Button onClick={saveSub}>ذخیره وضعیت اشتراک</Button></CardContent></Card></TabsContent>
    </Tabs>
  </div>;
}
